import { Component, Input, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { MatButtonModule } from '@angular/material/button';
import { MatIconModule } from '@angular/material/icon';
import { MatTooltipModule } from '@angular/material/tooltip';

import {
  MsimAuthoringService,
  SimDefLite,
} from '@services/multi-scale/msim-authoring.service';

interface ChoiceRow {
  key: string;
  label: string;
  description: string;
  setParamsText: string;      // "mass=16.8, bob_radius=0.08"
  enabled: boolean;
  disabledReason: string;
}
interface DerivedRow { name: string; expr: string; }

/**
 * Overall-ICs editor — the configured initial-condition interfaces
 * (e.g. the bob material picker). Choices map a plain-language pick to
 * parameter bundles; disabled choices carry their reason (and, when a
 * first-principles search exhausted, its data). Milestone B replaces
 * hand-authored choices with ones generated by the material space —
 * same shape.
 */
@Component({
  standalone: true,
  selector: 'msim-ic-editor',
  imports: [CommonModule, FormsModule, MatButtonModule, MatIconModule, MatTooltipModule],
  template: `
    <div class="editor-intro">
      Initial-condition interfaces: purpose-built pickers that set a
      simulation's starting parameters. Every selection re-validates
      automatically. A disabled choice stays visible with the reason the
      physics refused it.
    </div>

    <div class="field-row">
      <label>interface</label>
      <select class="select-input" [(ngModel)]="selectedName" (ngModelChange)="loadSelected()">
        <option *ngFor="let n of interfaceNames" [value]="n">{{ n }}</option>
      </select>
      <button mat-stroked-button (click)="startNew()"><mat-icon>add</mat-icon> new interface</button>
    </div>

    <div class="item-card" *ngIf="editing">
      <div class="field-row">
        <label>name</label>
        <input class="text-input grow" [(ngModel)]="name" [disabled]="!!editingId" />
        <label>shown as</label>
        <input class="text-input" [(ngModel)]="label" placeholder="e.g. Bob material" />
      </div>
      <div class="field-row">
        <label>sets initial conditions of</label>
        <select class="select-input" [(ngModel)]="targetSim">
          <option *ngFor="let s of sims" [value]="s.name">{{ s.name }}</option>
        </select>
        <select class="select-input" [(ngModel)]="targetClass">
          <option value="">(state class)</option>
          <option *ngFor="let c of classesOf(targetSim)" [value]="c">{{ c }}</option>
        </select>
      </div>

      <div class="subsection">
        <div class="subsection-head">
          Choices
          <button mat-icon-button (click)="choices.push({key:'', label:'', description:'', setParamsText:'', enabled:true, disabledReason:''})">
            <mat-icon>add</mat-icon></button>
        </div>
        <div class="item-card" *ngFor="let c of choices; let ci = index">
          <div class="field-row">
            <label>key</label>
            <input class="text-input" [(ngModel)]="c.key" />
            <label>label</label>
            <input class="text-input" [(ngModel)]="c.label" />
            <label class="chk"><input type="checkbox" [(ngModel)]="c.enabled" /> available</label>
            <button mat-icon-button (click)="choices.splice(ci, 1)"><mat-icon>close</mat-icon></button>
          </div>
          <div class="field-row">
            <label>sets parameters</label>
            <input class="text-input grow" placeholder="mass=16.84, bob_radius=0.08"
                   [(ngModel)]="c.setParamsText" />
          </div>
          <div class="field-row" *ngIf="!c.enabled">
            <label>why it is disabled</label>
            <input class="text-input grow"
                   placeholder="plain-language reason (a first-principles search fills this + its data automatically)"
                   [(ngModel)]="c.disabledReason" />
          </div>
        </div>
      </div>

      <div class="subsection">
        <div class="subsection-head">
          Derived geometry (recomputed from the chosen parameters)
          <button mat-icon-button (click)="derived.push({name:'', expr:''})">
            <mat-icon>add</mat-icon></button>
        </div>
        <div class="field-row" *ngFor="let d of derived; let di = index">
          <input class="text-input" placeholder="e.g. bob_cross_section" [(ngModel)]="d.name" />
          <label>=</label>
          <input class="text-input grow" placeholder="e.g. pi * bob_radius ** 2" [(ngModel)]="d.expr" />
          <button mat-icon-button (click)="derived.splice(di, 1)"><mat-icon>close</mat-icon></button>
        </div>
      </div>

      <div class="editor-actions">
        <button mat-flat-button color="primary" [disabled]="saving || !name" (click)="save()">
          <mat-icon>save</mat-icon> Save interface
        </button>
        <span class="hint" *ngIf="saveMessage">{{ saveMessage }}</span>
      </div>
    </div>
  `,
  styleUrls: ['./msim-editors.scss'],
})
export class MsimIcEditorComponent implements OnInit {
  @Input() initialName = '';

  interfaceNames: string[] = [];
  sims: SimDefLite[] = [];
  private rows: any[] = [];

  editing = false;
  editingId = '';
  selectedName = '';
  name = '';
  label = '';
  targetSim = '';
  targetClass = '';
  choices: ChoiceRow[] = [];
  derived: DerivedRow[] = [];
  saving = false;
  saveMessage: string | null = null;

  constructor(private authoring: MsimAuthoringService) {}

  async ngOnInit(): Promise<void> {
    this.sims = await this.authoring.listSimDefs();
    await this.reloadList();
    this.selectedName = this.initialName || this.interfaceNames[0] || '';
    if (this.selectedName) this.loadSelected();
  }

  private async reloadList(): Promise<void> {
    this.rows = await this.authoring.listIcInterfaces();
    this.interfaceNames = this.rows.map(r => r.name).filter(Boolean);
  }

  classesOf(simName: string): string[] {
    return this.sims.find(s => s.name === simName)?.participatingClasses ?? [];
  }

  startNew(): void {
    this.editing = true;
    this.editingId = '';
    this.name = '';
    this.label = '';
    this.targetSim = this.sims[0]?.name ?? '';
    this.targetClass = '';
    this.choices = [];
    this.derived = [];
    this.saveMessage = null;
  }

  loadSelected(): void {
    const row = this.rows.find(r => r.name === this.selectedName);
    if (!row) return;
    let cfg: any = {};
    try { cfg = JSON.parse(row.config_json || '{}'); } catch { cfg = {}; }
    this.editing = true;
    this.editingId = row.id ?? '';
    this.name = row.name ?? '';
    this.label = cfg.label ?? '';
    this.targetSim = row.target_simulation_ref ?? '';
    this.targetClass = row.target_class_name ?? '';
    this.choices = (Array.isArray(cfg.choices) ? cfg.choices : []).map((c: any) => ({
      key: c.key ?? '', label: c.label ?? '', description: c.description ?? '',
      setParamsText: Object.entries(c.setParams ?? {})
        .map(([k, v]) => `${k}=${v}`).join(', '),
      enabled: c.enabled !== false,
      disabledReason: c.disabledReason ?? '',
    }));
    this.derived = Object.entries(cfg.derivedParams ?? {})
      .map(([name, expr]) => ({ name, expr: String(expr) }));
    this.saveMessage = null;
  }

  async save(): Promise<void> {
    this.saving = true;
    this.saveMessage = null;
    const choices = this.choices.filter(c => c.key).map(c => {
      const setParams: Record<string, number> = {};
      for (const part of c.setParamsText.split(',')) {
        const [k, v] = part.split('=').map(s => s.trim());
        if (k && v !== undefined && !isNaN(Number(v))) setParams[k] = Number(v);
      }
      const out: any = {
        key: c.key, label: c.label || c.key,
        description: c.description, setParams,
      };
      if (!c.enabled) {
        out.enabled = false;
        out.disabledReason = c.disabledReason
          || 'No valid solution was found for this choice.';
      }
      return out;
    });
    const derivedParams: Record<string, string> = {};
    for (const d of this.derived) {
      if (d.name && d.expr) derivedParams[d.name] = d.expr;
    }
    try {
      await this.authoring.saveIcInterface(this.editingId, {
        name: this.name,
        description: this.label,
        target_simulation_ref: this.targetSim,
        target_class_name: this.targetClass,
        interface_kind: 'choicePreset',
        config_json: JSON.stringify({ label: this.label, choices, derivedParams }),
        enabled: true,
      });
      this.saveMessage = 'Saved.';
      await this.reloadList();
      if (!this.editingId) this.selectedName = this.name;
    } catch (err: any) {
      this.saveMessage = `Save failed: ${err?.message || err}`;
    } finally {
      this.saving = false;
    }
  }
}
