import { CommonModule } from '@angular/common';
import { Component, Input } from '@angular/core';

/** One rendered C source line with its autogenerated datasheet comment (ucd-iso: cmod's `/code` door). */
export interface CodeBlockLine {
  n: number;
  text: string;
  comment?: string;
}

/**
 * code-block — a reusable monospace code panel (ucd-iso-1, his ruling 2026-10-10: "a code-interface that shows it
 * as though it is actual c-code … with comment that should autogenerate saying which data-sheet they should come
 * from"). No syntax-highlighting library — theme tokens only, newlines preserved, one "copy" control.
 *
 * Two shapes of input, either one:
 *   - `text`: a plain multi-line string (a CIsotope's `source`, or any `col:code` table cell).
 *   - `lines`: numbered lines with a per-line autogenerated `comment`, shown right-aligned and muted on that
 *     line (the CFunctionAtom code-interface's `lines[]`, preferred there over the flat `rendered` string so the
 *     comment can be styled apart from the code).
 * `lines` wins when both are given.
 */
@Component({
  standalone: true,
  selector: 'code-block',
  imports: [CommonModule],
  template: `
    <div class="code-block">
      <div class="code-block-bar">
        <button type="button" class="copy" (click)="copy()">{{ copied ? 'copied' : 'copy' }}</button>
      </div>
      <pre *ngIf="lines && lines.length; else plainBlock"><div class="line" *ngFor="let l of lines"><span class="n">{{ l.n }}</span><span class="t">{{ l.text }}</span><span class="c" *ngIf="l.comment">{{ l.comment }}</span></div></pre>
      <ng-template #plainBlock><pre class="plain">{{ text }}</pre></ng-template>
    </div>
  `,
  styles: [`
    .code-block { position: relative; border-radius: 8px; background: var(--surface-alt, #f4f4f4); }
    .code-block-bar { display: flex; justify-content: flex-end; padding: 4px 6px 0; }
    button.copy {
      padding: 2px 10px; border: 1px solid var(--border-medium, #ddd); border-radius: 10px;
      background: var(--surface-variant, #eee); color: var(--text-secondary, #666);
      font: inherit; font-size: .78em; cursor: pointer;
    }
    button.copy:hover { background: var(--surface-hover, #e4e4e4); }
    pre {
      margin: 0; padding: 4px 12px 10px; overflow-x: auto; font-family: var(--font-mono, monospace);
      font-size: .88em; line-height: 1.5; white-space: pre;
    }
    pre.plain { white-space: pre-wrap; }
    .line { display: flex; gap: 10px; white-space: pre; }
    .line .n { flex: 0 0 auto; min-width: 2.2em; text-align: right; color: var(--text-tertiary, #999); user-select: none; }
    .line .t { flex: 0 1 auto; white-space: pre; }
    .line .c { flex: 1 1 auto; text-align: right; color: var(--text-secondary, #666); font-style: italic; white-space: nowrap; padding-left: 16px; }
  `],
})
export class CodeBlockComponent {
  @Input() text = '';
  @Input() lines: CodeBlockLine[] | null = null;

  copied = false;

  copy(): void {
    const payload = this.lines && this.lines.length ? this.lines.map((l) => l.text).join('\n') : this.text;
    const done = () => { this.copied = true; setTimeout(() => { this.copied = false; }, 1200); };
    if (navigator.clipboard?.writeText) {
      navigator.clipboard.writeText(payload || '').then(done).catch(() => { /* clipboard denied — the text is still selectable */ });
    }
  }
}
